export const EVENTS_AVAILABLE_FOR_USERS = {
    "events": [
      {
        "id": "4f57a8bc1d3e6f9b",
        "title": "Art show 🎨",
        "host": "Olivia Adams",
        "date": "Monday, Nov 13 2023",
        "start_time": "6:00 PM",
        "end_time": "10:00 PM",
        "location": "Lower Manhattan",
        "address_info": "Join to see full address",
        "tickets_left": 78,
        "total_tickets": 100,
        "invited_count": 100,
        "min_price": 10.00,
        "max_price": 50.00,
        "currency": "USD",
        "currency_symbol": "$",
        "about": "Come join me in celebrating my 25th birthday! I can't wait to celebrate with all of you, so let's make it a night to remember. See you at the party!",
        "find_event": null
      },
      {
        "id": "9e45bc723f8a1d67",
        "title": "Jazz Night 🎷",
        "host": "John Doe",
        "date": "Friday, Dec 1 2023",
        "start_time": "7:00 PM",
        "end_time": "11:00 PM",
        "location": "Brooklyn",
        "address_info": "Join to see full address",
        "tickets_left": 45,
        "total_tickets": 80,
        "invited_count": 150,
        "min_price": 15.00,
        "max_price": 40.00,
        "currency": "USD",
        "currency_symbol": "$",
        "about": "Enjoy an evening of smooth jazz with John Doe and his band. Don't miss out on this musical extravaganza.",
        "find_event": null,
        "currentUserStatus": "APPROVED"
      },
      {
        "id": "3b8ef7a92d6e5c14",
        "title": "Comedy Show 😂",
        "host": "Emily Clark",
        "date": "Saturday, Dec 2 2023",
        "start_time": "8:00 PM",
        "end_time": "10:00 PM",
        "location": "Queens",
        "address_info": "Join to see full address",
        "tickets_left": 60,
        "total_tickets": 100,
        "invited_count": 200,
        "min_price": 20.00,
        "max_price": 60.00,
        "currency": "USD",
        "currency_symbol": "$",
        "about": "Get ready to laugh all night with Emily Clark and her hilarious friends. It's a show you won't want to miss.",
        "find_event": null
      },
      {
        "id": "1d3f7a8c9b5e2f46",
        "title": "Tech Meetup 💻",
        "host": "David Smith",
        "date": "Wednesday, Nov 29 2023",
        "start_time": "6:30 PM",
        "end_time": "9:30 PM",
        "location": "Silicon Alley",
        "address_info": "Join to see full address",
        "tickets_left": 85,
        "total_tickets": 120,
        "invited_count": 250,
        "min_price": 5.00,
        "max_price": 25.00,
        "currency": "USD",
        "currency_symbol": "$",
        "about": "Join us for an evening of tech talks and networking. Meet industry leaders and like-minded tech enthusiasts.",
        "find_event": null
      },
      {
        "id": "5b6e8a9d1f2c3b78",
        "title": "Yoga Retreat 🧘‍♀️",
        "host": "Sophia Brown",
        "date": "Sunday, Dec 10 2023",
        "start_time": "10:00 AM",
        "end_time": "4:00 PM",
        "location": "Central Park",
        "address_info": "Join to see full address",
        "tickets_left": 30,
        "total_tickets": 50,
        "invited_count": 80,
        "min_price": 30.00,
        "max_price": 100.00,
        "currency": "USD",
        "currency_symbol": "$",
        "about": "Relax and rejuvenate with a day of yoga and meditation led by Sophia Brown. All levels are welcome.",
        "find_event": null
      },
      {
        "id": "8c9d1f2e4b6a5f3c",
        "title": "Cooking Class 🍳",
        "host": "Chef Michael",
        "date": "Tuesday, Dec 5 2023",
        "start_time": "5:00 PM",
        "end_time": "8:00 PM",
        "location": "SoHo",
        "address_info": "Join to see full address",
        "tickets_left": 20,
        "total_tickets": 40,
        "invited_count": 60,
        "min_price": 50.00,
        "max_price": 150.00,
        "currency": "USD",
        "currency_symbol": "$",
        "about": "Learn to cook gourmet dishes with Chef Michael. Ingredients and materials provided.",
        "find_event": null
      },
      {
        "id": "7f3c1d2e8b9a6f5d",
        "title": "Photography Workshop 📸",
        "host": "Lisa Wong",
        "date": "Thursday, Nov 30 2023",
        "start_time": "3:00 PM",
        "end_time": "6:00 PM",
        "location": "Harlem",
        "address_info": "Join to see full address",
        "tickets_left": 10,
        "total_tickets": 25,
        "invited_count": 40,
        "min_price": 75.00,
        "max_price": 200.00,
        "currency": "USD",
        "currency_symbol": "$",
        "about": "Improve your photography skills with expert tips and hands-on practice in a supportive environment.",
        "find_event": null
      },
      {
        "id": "2f4b6a9d8c7e1f3b",
        "title": "Book Reading 📚",
        "host": "Author Jane",
        "date": "Saturday, Dec 9 2023",
        "start_time": "2:00 PM",
        "end_time": "4:00 PM",
        "location": "Greenwich Village",
        "address_info": "Join to see full address",
        "tickets_left": 25,
        "total_tickets": 50,
        "invited_count": 70,
        "min_price": 10.00,
        "max_price": 30.00,
        "currency": "USD",
        "currency_symbol": "$",
        "about": "Join Author Jane for a reading from her latest novel, followed by a Q&A session and book signing.",
        "find_event": null
      },
      {
        "id": "6e4b9a7c3f1d2b5e",
        "title": "Dance Party 💃",
        "host": "DJ Alex",
        "date": "Friday, Dec 8 2023",
        "start_time": "9:00 PM",
        "end_time": "2:00 AM",
        "location": "Midtown",
        "address_info": "Join to see full address",
        "tickets_left": 100,
        "total_tickets": 200,
        "invited_count": 300,
        "min_price": 20.00,
        "max_price": 80.00,
        "currency": "USD",
        "currency_symbol": "$",
        "about": "Dance the night away with DJ Alex spinning the latest hits. Don't miss this unforgettable night.",
        "find_event": null
      },
      {
        "id": "1f2e3b6a9d8c5f7d",
        "title": "Charity Gala 🎩",
        "host": "Emma Williams",
        "date": "Saturday, Dec 16 2023",
        "start_time": "7:00 PM",
        "end_time": "12:00 AM",
        "location": "Upper East Side",
        "address_info": "Join to see full address",
        "tickets_left": 150,
        "total_tickets": 250,
        "invited_count": 400,
        "min_price": 100.00,
        "max_price": 500.00,
        "currency": "USD",
        "currency_symbol": "$",
        "about": "Join us for an elegant evening of dining and dancing, all for a good cause. Formal attire required.",
        "find_event": null
      }
    ]
  }
  